"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/research/templates.py
Markdown templates for research summaries.
Author : Jules
License: MIT
"""

from string import Template

RESEARCH_SUMMARY_TEMPLATE = Template("""
# Research Summary: ${report_id}
**Generated on:** ${timestamp}

## Overall Sentiment: ${overall_sentiment}

## Key Recommendations
${key_recommendations}

---

## Regime Analysis
${regime_analysis}

## Allocation Insights
${allocations}

## Trade Pattern Findings
${trade_patterns}

## Stress Test Outcomes
${stress_tests}

## Hyperparameter Robustness
${hyperparameter_robustness}

## Model Drift Observations
${model_drift}

## Benchmark Comparisons
${benchmarks}

---
*Generated by MT5 AI/ML Research Reporting Engine*
""")

REGIME_REPORT_TEMPLATE = Template("""
- **Current Regime:** ${current_regime}
- **Confidence:** ${confidence_pct}%
- **Characteristics:** ${characteristics}
- **Transition Probabilities:** ${transitions}
""")

ALLOCATION_REPORT_TEMPLATE = Template("""
- **Symbol:** ${symbol}
  - Weight: ${current_weight_pct}% (Target: ${target_weight_pct}%)
  - Risk Contribution: ${risk_contribution_pct}%
  - Leverage: ${leverage_used}x
""")

PATTERN_REPORT_TEMPLATE = Template("""
- **Pattern:** ${pattern_name}
  - Frequency: ${frequency}
  - Win Rate: ${win_rate_pct}%
  - Profit Factor: ${profit_factor}
  - Avg Holding Time: ${avg_holding_time} mins
""")

STRESS_TEST_TEMPLATE = Template("""
- **Scenario:** ${scenario_name}
  - Max Drawdown: ${max_drawdown_pct}%
  - Recovery Factor: ${recovery_factor}
  - Resilience Score: ${resilience_score}
  - Failure Points: ${failure_points}
""")

HYPERPARAMETER_TEMPLATE = Template("""
- **Parameter:** ${parameter_name}
  - Sensitivity: ${sensitivity_score}
  - Optimal Range: ${optimal_range}
  - Stability: ${stability_metric}
""")

DRIFT_TEMPLATE = Template("""
- **Model:** ${model_id}
  - Feature Drift: ${feature_drift_score}
  - Prediction Drift: ${prediction_drift_score}
  - Recalibration Recommended: ${recalibration}
  - Affected Features: ${affected_features}
""")

BENCHMARK_TEMPLATE = Template("""
- **Benchmark:** ${benchmark_name}
  - Alpha: ${alpha}
  - Beta: ${beta}
  - Info Ratio: ${information_ratio}
  - Tracking Error: ${tracking_error}
""")
