"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/research/templates.py
Markdown templates for research reporting.
Author : triqbit
License: MIT
"""

RESEARCH_REPORT_TEMPLATE = """# Research Report: {report_id}
Generated by {author} on {timestamp}

## 📝 Executive Summary
{summary}

## 📊 Market Regime Analysis
| Regime | Prevalence | Accuracy | Sharpe | Max DD | Notes |
| :--- | :--- | :--- | :--- | :--- | :--- |
{regime_rows}

## 🛡️ Stress Test Outcomes
| Scenario | Resilience | Max DD | Recovery (steps) | Status | Observations |
| :--- | :--- | :--- | :--- | :--- | :--- |
{stress_rows}

## ⚙️ Hyperparameter Robustness
| Parameter | Optimal Value | Sensitivity | OOS Consistency |
| :--- | :--- | :--- | :--- |
{hyper_rows}

## 🔍 Trade Pattern Findings
| Pattern | Frequency | Win Rate | Profit Factor | Significance |
| :--- | :--- | :--- | :--- | :--- |
{pattern_rows}

## 📉 Model Drift Observations
| Feature Group | Drift Score | P-Value | Accuracy Impact | Action |
| :--- | :--- | :--- | :--- | :--- |
{drift_rows}

## 💰 Allocation & Weighting Insights
| Strategy | Current Weight | Recommended | Reasoning |
| :--- | :--- | :--- | :--- |
{allocation_rows}

## 🏁 Benchmark Comparisons
| Benchmark | Rel. Return | Rel. Sharpe | Win Rate Diff |
| :--- | :--- | :--- | :--- |
{benchmark_rows}

---
*Generated by MT5 AI/ML Trading Bot - Research Reporting Engine*
"""
