"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/research/templates.py
Markdown templates for research reporting.
Author : triqbit
License: MIT
"""

MAIN_REPORT_TEMPLATE = """# Institutional Research Summary: {title}
**Date:** {date}
**Author:** {author}
**System Version:** {version}

---

## 1. Executive Summary
{executive_summary}

## 2. Market Regime Analysis
{regime_analysis}

## 3. Stress Test Outcomes
{stress_tests}

## 4. Hyperparameter Robustness
{hyperparameter_robustness}

## 5. Trade Pattern Findings
{trade_patterns}

## 6. Model Drift & Calibration
{model_drift}

## 7. Capital Allocation Insights
{allocation_insights}

## 8. Benchmark Comparisons
{benchmarks}

---
*Generated by MT5 AI/ML Trading Bot - Research Reporting Engine*
"""

REGIME_TABLE_HEADER = "| Regime | Occurrences | Avg Profit | Win Rate | Max Drawdown |"
REGIME_TABLE_ROW = "| {regime} | {count} | {avg_profit:.2f} | {win_rate:.2%} | {max_dd:.2f} |"

STRESS_TEST_TABLE_HEADER = "| Scenario | Resilience Score | Max Drawdown | Recovery Time | Outcome |"
STRESS_TEST_TABLE_ROW = "| {scenario} | {score:.2f} | {max_dd:.2f} | {recovery} | {outcome} |"

HYPEROPT_TABLE_HEADER = "| Parameter | Optimal Value | Stability Score | Range Tested |"
HYPEROPT_TABLE_ROW = "| {param} | {value} | {stability:.2f} | {range} |"

TRADE_PATTERN_TABLE_HEADER = "| Pattern ID | Frequency | Edge (Pips) | Significance | Status |"
TRADE_PATTERN_TABLE_ROW = "| {pattern_id} | {frequency} | {edge:.1f} | {significance:.2f} | {status} |"

DRIFT_TABLE_HEADER = "| Model | Calibration Error | PSI | Performance Decay | Action Required |"
DRIFT_TABLE_ROW = "| {model} | {error:.4f} | {psi:.4f} | {decay:.2%} | {action} |"

ALLOCATION_TABLE_HEADER = "| Strategy | Assigned Capital | Utilisation | Risk Contribution | Multiplier |"
ALLOCATION_TABLE_ROW = "| {strategy} | {capital:.2f} | {utilisation:.2%} | {risk_contrib:.2%} | {multiplier:.2f} |"

BENCHMARK_TABLE_HEADER = "| Metric | System | Benchmark | Relative Alpha |"
BENCHMARK_TABLE_ROW = "| {metric} | {system_val:.2f} | {bench_val:.2f} | {alpha:.2%} |"
