import json
import subprocess
import os
from datetime import datetime

def get_json(url):
    cmd = ["curl", "-s", url]
    res = subprocess.run(cmd, capture_output=True, text=True)
    try:
        data = json.loads(res.stdout)
        return data
    except:
        return None

def classify(files):
    high_risk_dirs = ['src/trading/', 'src/models/', 'src/core/config.py', 'migrations/']
    high_risk_files = ['main.py', 'alembic.ini', 'pyproject.toml']
    medium_risk_dirs = ['src/research/', 'src/analytics/', 'src/core/']
    safe_dirs = ['docs/', 'tests/', 'README.md', '.github/', 'scripts/']

    risk = "Safe Surface"
    matched_any = False
    for f in files:
        if any(f.startswith(d) for d in high_risk_dirs) or f in high_risk_files:
            return "High Risk"
        if any(f.startswith(d) for d in medium_risk_dirs):
            risk = "Medium Risk"
            matched_any = True
        elif any(f.startswith(d) for d in safe_dirs):
            matched_any = True

    if not matched_any and files:
        risk = "Medium Risk"

    return risk

def get_ci_status(repo_full_name, ref):
    url = f"https://api.github.com/repos/{repo_full_name}/commits/{ref}/check-runs"
    data = get_json(url)
    if not data or not isinstance(data, dict) or "check_runs" not in data:
        return "Unknown"

    runs = data["check_runs"]
    if not runs:
        return "No CI"

    for run in runs:
        if run["status"] != "completed":
            return "Pending"
        if run["conclusion"] != "success":
            return "Fail"
    return "Pass"

repo = "triqbit/mt5-ai-xauusd-trader"
pulls = get_json(f"https://api.github.com/repos/{repo}/pulls")
if not pulls or not isinstance(pulls, list):
    print("Failed to fetch PRs")
    exit(1)

report_data = []
for p in pulls:
    num = p["number"]
    title = p["title"]
    user = p["user"]["login"]
    html_url = p["html_url"]
    ref = p["head"]["sha"]

    files_data = get_json(f"https://api.github.com/repos/{repo}/pulls/{num}/files")
    files = []
    if isinstance(files_data, list):
        files = [f["filename"] for f in files_data]

    risk = classify(files)
    ci_status = get_ci_status(repo, ref)

    areas = ", ".join(list(set([f.split('/')[0] if '/' in f else f for f in files]))[:3])

    report_data.append({
        "num": num,
        "title": title,
        "user": user,
        "risk": risk,
        "status": ci_status,
        "areas": areas,
        "url": html_url
    })

recommendations = [p for p in report_data if p["risk"] in ["Safe Surface", "Medium Risk"] and p["status"] == "Pass"][:4]
if not recommendations:
    recommendations = [p for p in report_data if p["risk"] in ["Safe Surface", "Medium Risk"]][:4]

now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

print(f"# Daily PR Triage Dashboard - {now}")
print("\n## Overview")
print("| PR # | Title | Author | Risk Class | Status | Touched Areas |")
print("|---|---|---|---|---|---|")
for p in report_data:
    status_emoji = "✅" if p['status'] == "Pass" else "❌" if p['status'] == "Fail" else "⏳" if p['status'] == "Pending" else "❓"
    print(f"| [{p['num']}]({p['url']}) | {p['title']} | {p['user']} | **{p['risk']}** | {status_emoji} {p['status']} | {p['areas']} |")

print("\n## Recommendations for Review Today")
if recommendations:
    for r in recommendations:
        print(f"- **#{r['num']}**: {r['title']} (Risk: {r['risk']}, Status: {r['status']})")
else:
    print("No safe/medium risk candidates identified today.")

print("\n---")
print("*Generated by Jules06 (qufuwan)*")
