"""Add signal_source and make ticket nullable in trades

Revision ID: 0d5388492b27
Revises: ad2c762996af
Create Date: 2026-05-09 13:03:29.717934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5388492b27'
down_revision: Union[str, None] = 'ad2c762996af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_signal_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_cost_pnl', sa.Float(), nullable=False),
    sa.Column('max_favorable_excursion', sa.Float(), nullable=False),
    sa.Column('max_adverse_excursion', sa.Float(), nullable=False),
    sa.Column('would_have_won', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['model_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    with op.batch_alter_table('blocked_signal_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_signal_analysis_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_signal_analysis_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('execution_qualities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('slippage_pips', sa.Float(), nullable=False),
    sa.Column('execution_latency_ms', sa.Float(), nullable=False),
    sa.Column('fill_quality_score', sa.Float(), nullable=False),
    sa.Column('edge_capture', sa.Float(), nullable=False),
    sa.Column('timing_efficiency', sa.Float(), nullable=False),
    sa.Column('alpha_decay_pips', sa.Float(), nullable=False),
    sa.Column('execution_cost_pips', sa.Float(), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=True),
    sa.Column('markout_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    with op.batch_alter_table('execution_qualities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_qualities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_qualities_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volatility', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trace_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_model_signals_trace_id'), ['trace_id'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trace_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('ticket',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_trades_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_trace_id'))
        batch_op.alter_column('ticket',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('trace_id')
        batch_op.drop_column('signal_source')

    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_signals_trace_id'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('trace_id')
        batch_op.drop_column('volatility')

    with op.batch_alter_table('execution_qualities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_qualities_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_execution_qualities_created_at'))

    op.drop_table('execution_qualities')
    with op.batch_alter_table('blocked_signal_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_signal_analysis_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_blocked_signal_analysis_created_at'))

    op.drop_table('blocked_signal_analysis')
    # ### end Alembic commands ###
