"""Remove is_deleted from AuditMixin

Revision ID: 1624622f0670
Revises: d63b57d20962
Create Date: 2026-04-22 12:42:21.856766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1624622f0670'
down_revision: Union[str, None] = 'd63b57d20962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_signals', 'is_deleted')
    op.drop_column('performance_metrics', 'is_deleted')
    op.drop_column('risk_events', 'is_deleted')
    op.drop_column('trades', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('risk_events', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('performance_metrics', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('model_signals', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
