"""Add audit columns and constraints

Revision ID: 2c74982b8d32
Revises: c1b7f28e5748
Create Date: 2026-05-01 21:33:04.191944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c74982b8d32'
down_revision: Union[str, None] = 'c1b7f28e5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volatility', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_model_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_signals_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_check_constraint('check_signal_entry_price_positive', 'entry_price > 0')
        batch_op.create_check_constraint('check_signal_lot_size_positive', 'lot_size > 0')
        batch_op.create_check_constraint('check_signal_direction_valid', 'direction IN (-1, 0, 1)')

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_performance_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_metrics_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_risk_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_check_constraint('check_trade_entry_price_positive', 'entry_price > 0')
        batch_op.create_check_constraint('check_trade_lot_size_positive', 'lot_size > 0')
        batch_op.create_check_constraint('check_trade_direction_valid', 'direction IN (-1, 1)')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('check_trade_direction_valid', type_='check')
        batch_op.drop_constraint('check_trade_lot_size_positive', type_='check')
        batch_op.drop_constraint('check_trade_entry_price_positive', type_='check')
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_trades_created_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_risk_events_created_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_performance_metrics_created_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.drop_constraint('check_signal_direction_valid', type_='check')
        batch_op.drop_constraint('check_signal_lot_size_positive', type_='check')
        batch_op.drop_constraint('check_signal_entry_price_positive', type_='check')
        batch_op.drop_index(batch_op.f('ix_model_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_model_signals_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_model_signals_created_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('volatility')

    # ### end Alembic commands ###
