"""update_trade_logger_standards

Revision ID: 437d02adbde2
Revises: c1b7f28e5748
Create Date: 2026-04-29 13:13:16.147297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437d02adbde2'
down_revision: Union[str, None] = 'c1b7f28e5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_signals', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('model_signals', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('model_signals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('performance_metrics', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('performance_metrics', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('performance_metrics', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('risk_events', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('risk_events', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('risk_events', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('entry_time', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('exit_time', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('signal_source', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'deleted_at')
    op.drop_column('trades', 'updated_by')
    op.drop_column('trades', 'created_by')
    op.drop_column('trades', 'signal_source')
    op.drop_column('trades', 'exit_time')
    op.drop_column('trades', 'entry_time')
    op.drop_column('risk_events', 'deleted_at')
    op.drop_column('risk_events', 'updated_by')
    op.drop_column('risk_events', 'created_by')
    op.drop_column('performance_metrics', 'deleted_at')
    op.drop_column('performance_metrics', 'updated_by')
    op.drop_column('performance_metrics', 'created_by')
    op.drop_column('model_signals', 'deleted_at')
    op.drop_column('model_signals', 'updated_by')
    op.drop_column('model_signals', 'created_by')
    # ### end Alembic commands ###
