"""make_ticket_nullable_add_signal_source

Revision ID: 83088587be2d
Revises: ad2c762996af
Create Date: 2026-05-07 19:21:38.424591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83088587be2d'
down_revision: Union[str, None] = 'ad2c762996af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volatility', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_source', sa.String(length=50), nullable=True))
        batch_op.alter_column('ticket',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('ticket',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('signal_source')

    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('volatility')

    # ### end Alembic commands ###
