"""Sync schema and add trace_id to audit_log

Revision ID: 8cbb2c70ac2e
Revises: c1b7f28e5748
Create Date: 2026-05-05 07:57:50.611424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbb2c70ac2e'
down_revision: Union[str, None] = 'c1b7f28e5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.add_column('model_signals', sa.Column('volatility', sa.Float(), nullable=True))
    op.create_index(op.f('ix_model_signals_created_at'), 'model_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_signals_is_deleted'), 'model_signals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_model_signals_symbol'), 'model_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_performance_metrics_created_at'), 'performance_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_performance_metrics_is_deleted'), 'performance_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_is_deleted'), 'risk_events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_is_deleted'), 'trades', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_is_deleted'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_index(op.f('ix_risk_events_is_deleted'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_index(op.f('ix_performance_metrics_is_deleted'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_created_at'), table_name='performance_metrics')
    op.drop_index(op.f('ix_model_signals_symbol'), table_name='model_signals')
    op.drop_index(op.f('ix_model_signals_is_deleted'), table_name='model_signals')
    op.drop_index(op.f('ix_model_signals_created_at'), table_name='model_signals')
    op.drop_column('model_signals', 'volatility')
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
