"""add audit columns and constraints

Revision ID: a249de266d90
Revises: c1b7f28e5748
Create Date: 2026-05-02 13:31:13.726071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a249de266d90'
down_revision: Union[str, None] = 'c1b7f28e5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_signals', sa.Column('volatility', sa.Float(), nullable=True))
    op.add_column('model_signals', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('model_signals', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('model_signals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_model_signals_created_at'), 'model_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_signals_is_deleted'), 'model_signals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_model_signals_symbol'), 'model_signals', ['symbol'], unique=False)
    op.add_column('performance_metrics', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('performance_metrics', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('performance_metrics', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_performance_metrics_created_at'), 'performance_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_performance_metrics_is_deleted'), 'performance_metrics', ['is_deleted'], unique=False)
    op.add_column('risk_events', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('risk_events', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('risk_events', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_is_deleted'), 'risk_events', ['is_deleted'], unique=False)
    op.add_column('trades', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_is_deleted'), 'trades', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_is_deleted'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_column('trades', 'deleted_at')
    op.drop_column('trades', 'updated_by')
    op.drop_column('trades', 'created_by')
    op.drop_index(op.f('ix_risk_events_is_deleted'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_column('risk_events', 'deleted_at')
    op.drop_column('risk_events', 'updated_by')
    op.drop_column('risk_events', 'created_by')
    op.drop_index(op.f('ix_performance_metrics_is_deleted'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_created_at'), table_name='performance_metrics')
    op.drop_column('performance_metrics', 'deleted_at')
    op.drop_column('performance_metrics', 'updated_by')
    op.drop_column('performance_metrics', 'created_by')
    op.drop_index(op.f('ix_model_signals_symbol'), table_name='model_signals')
    op.drop_index(op.f('ix_model_signals_is_deleted'), table_name='model_signals')
    op.drop_index(op.f('ix_model_signals_created_at'), table_name='model_signals')
    op.drop_column('model_signals', 'deleted_at')
    op.drop_column('model_signals', 'updated_by')
    op.drop_column('model_signals', 'created_by')
    op.drop_column('model_signals', 'volatility')
    # ### end Alembic commands ###
