"""synchronize schema with models

Revision ID: c9072f5d50b6
Revises: 793b42b56ff8
Create Date: 2026-05-12 06:44:07.951674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9072f5d50b6'
down_revision: Union[str, None] = '793b42b56ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_signals_algorithm'), ['algorithm'], unique=False)
        batch_op.create_index('ix_model_signals_symbol_timestamp', ['symbol', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_signals_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_signals_timestamp'))
        batch_op.drop_index('ix_model_signals_symbol_timestamp')
        batch_op.drop_index(batch_op.f('ix_model_signals_algorithm'))

    # ### end Alembic commands ###
