"""Add timestamp to trades and performance_metrics

Revision ID: df890313c96e
Revises: 0d5388492b27
Create Date: 2026-05-09 13:11:24.795148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df890313c96e'
down_revision: Union[str, None] = '0d5388492b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_trades_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_timestamp'))

    # ### end Alembic commands ###
