"""update_trade_logger_schema

Revision ID: fd526f5fd187
Revises: c1b7f28e5748
Create Date: 2026-04-25 12:52:54.665464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd526f5fd187'
down_revision: Union[str, None] = 'c1b7f28e5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_model_signals_symbol_created_at', ['symbol', 'created_at'], unique=False)
        batch_op.create_check_constraint("check_signal_entry_price_positive", "entry_price > 0")
        batch_op.create_check_constraint("check_signal_lot_size_positive", "lot_size > 0")

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_risk_events_symbol_created_at', ['symbol', 'created_at'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_trades_symbol_created_at', ['symbol', 'created_at'], unique=False)
        batch_op.create_check_constraint("check_trade_entry_price_positive", "entry_price > 0")
        batch_op.create_check_constraint("check_trade_lot_size_positive", "lot_size > 0")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('check_trade_lot_size_positive', type_='check')
        batch_op.drop_constraint('check_trade_entry_price_positive', type_='check')
        batch_op.drop_index('idx_trades_symbol_created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index('idx_risk_events_symbol_created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.drop_constraint('check_signal_lot_size_positive', type_='check')
        batch_op.drop_constraint('check_signal_entry_price_positive', type_='check')
        batch_op.drop_index('idx_model_signals_symbol_created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
