"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/schemas/trading.py
Pydantic schemas for trading signals and execution.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ModelSignalSchema(BaseModel):
    """Raw signal generated by the ensemble model."""
    model_config = ConfigDict(frozen=True)

    symbol: str = Field(..., min_length=3, max_length=10)
    direction: Literal[1, -1, 0] = Field(..., description="+1 buy / -1 sell / 0 hold")
    entry_price: float = Field(..., gt=0)
    algorithm: str = Field(..., min_length=1)
    confidence: float = Field(..., ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TradeSignalSchema(BaseModel):
    """Validated trading signal passed to order execution."""
    model_config = ConfigDict(frozen=True)

    symbol: str = Field(..., min_length=3, max_length=10)
    direction: Literal[1, -1] = Field(..., description="+1 buy / -1 sell")
    entry_price: float = Field(..., gt=0)
    stop_loss: float = Field(..., gt=0)
    take_profit: float = Field(..., gt=0)
    lot_size: float = Field(..., ge=0.01)
    algorithm: str = Field(..., min_length=1)
    confidence: float = Field(..., ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TradeExecutionSchema(BaseModel):
    """Schema for executed trade results."""
    ticket: int = Field(..., gt=0)
    symbol: str
    direction: int
    entry_price: float = Field(..., gt=0)
    lot_size: float = Field(..., ge=0.01)
    status: str = "OPEN"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
