"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/core/decision_support.py

Structured operator-facing decision support system.
Provides institutional-grade decision packets before trade execution,
aggregating signal attribution, market regime, macro risk, and strategy performance.

Usage:
    dss = DecisionSupportSystem()
    packet = dss.assemble_packet(
        symbol="XAUUSD",
        explanation=explanation,
        regime_info=regime,
        macro_risk=macro,
        performance_metrics=metrics
    )
    dss.format_for_operator(packet, console=rich_console)

All data packets generated by this system are immutable (frozen) and enforce
strict Pydantic range constraints to ensure that the information presented
to the operator is both accurate and consistent.

Author : triqbit
License: MIT
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator

from src.core.constants import DecisionStatus, SignalDirection
from src.core.explainability import SignalExplainer, SignalExplanation
from src.data.event_models import RiskStatus
from src.models.regime_detector import RegimeInfo

logger = logging.getLogger(__name__)

__all__ = [
    "DecisionPacket",
    "DecisionSupportSystem",
    "PerformanceContext",
]


class PerformanceContext(BaseModel):
    """
    Recent performance metrics for the current strategy/account.
    Enables the operator to understand the strategy's current state.

    This model is immutable (frozen) and forbids extra fields to ensure
    performance metrics remain consistent and auditable.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    sharpe_ratio: float = Field(
        0.0,
        ge=-10.0,
        description="Risk-adjusted return (Sharpe Ratio). Target > 2.0 per standards.",
    )
    profit_factor: float = Field(
        0.0,
        ge=0.0,
        description="Gross Profit / Gross Loss. Target > 2.0 per standards.",
    )
    recovery_factor: float = Field(
        0.0,
        ge=0.0,
        description="Net Profit / Max Drawdown. Target > 2.0 per standards.",
    )
    win_rate: float = Field(
        0.0, ge=0.0, le=1.0, description="Percentage of winning trades (0.0 to 1.0)."
    )
    win_loss_ratio: float = Field(0.0, ge=0.0, description="Average Win / Average Loss.")
    sortino_ratio: float = Field(
        0.0,
        ge=-10.0,
        description="Downside risk-adjusted return. Target > 2.0 per standards.",
    )
    calmar_ratio: float = Field(
        0.0,
        ge=-10.0,
        description="Annualized Return / Max Drawdown. Target > 3.0 per standards.",
    )
    expectancy: float = Field(
        0.0,
        description="Expected value per trade in pips or currency units.",
    )
    sqn: float = Field(
        0.0,
        ge=-10.0,
        description="System Quality Number (Van Tharp). Score > 3 is considered excellent.",
    )
    max_drawdown: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="Maximum observed equity drawdown from peak to trough (0.0 to 1.0).",
    )
    cvar_95: float = Field(
        0.0,
        ge=-1.0,
        le=0.0,
        description="Conditional Value at Risk (Expected Shortfall) at 95% confidence.",
    )
    total_trades: int = Field(0, ge=0, description="Count of trades analyzed in this window.")


class DecisionPacket(BaseModel):
    """
    Unified packet for operator review before trade execution.
    Aggregates all critical dimensions of a trading decision for institutional trust.

    This model is immutable (frozen) and forbids extra fields.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the decision was finalized.",
    )
    symbol: str = Field(..., description="Target trading symbol (e.g., XAUUSD).")
    direction: SignalDirection = Field(
        ..., description="Consolidated signal direction from the ensemble."
    )
    consensus: str = Field(
        ..., description="Qualitative consensus level (e.g., 💪 Strong Majority)."
    )
    status_level: DecisionStatus = Field(
        DecisionStatus.BLOCKED, description="Augmented execution status for operator safety."
    )
    decision_score: float = Field(
        0.0, ge=0.0, le=100.0, description="Composite decision confidence score (0 to 100)."
    )
    consensus_score: float = Field(
        0.0, ge=0.0, le=40.0, description="Weighted ensemble consensus component (0-40)."
    )
    regime_score: float = Field(
        0.0, ge=0.0, le=30.0, description="Regime confidence and alignment component (0-30)."
    )
    risk_score: float = Field(
        0.0, ge=0.0, le=30.0, description="Risk/Reward and macro safety component (0-30)."
    )
    sizing_multiplier: float = Field(
        0.0, ge=0.0, le=1.0, description="Risk-based sizing multiplier (0.0 to 1.0)."
    )
    is_executable: bool = Field(
        False, description="Final binary decision on whether execution is permitted."
    )
    requires_review: bool = Field(
        False, description="Flag indicating if the decision requires manual operator review."
    )
    blocking_reasons: list[str] = Field(
        default_factory=list, description="Explicit reasons for blocking the trade, if any."
    )
    executive_summary: str = Field(
        "", description="High-level natural language summary of the decision rationale."
    )

    # Components
    explanation: SignalExplanation = Field(
        ..., description="Detailed signal attribution and machine-learning explainability."
    )
    regime: RegimeInfo = Field(..., description="Current market regime and volatility state.")
    macro_risk: RiskStatus = Field(..., description="Real-time macroeconomic risk intelligence.")
    performance: PerformanceContext = Field(
        ..., description="Recent performance metrics providing historical context."
    )

    @model_validator(mode="after")
    def validate_executable_state(self) -> DecisionPacket:
        """
        Enforce technical trust: a trade cannot be executable if it has blocking reasons
        or if the status level is BLOCKED.
        """
        if self.is_executable:
            if self.blocking_reasons:
                raise ValueError("Decision cannot be executable with active blocking reasons.")
            if self.status_level == DecisionStatus.BLOCKED:
                raise ValueError("Decision cannot be executable with a BLOCKED status level.")
        else:
            # If not executable, ensure consistency with status/reasons for clarity
            if self.status_level == DecisionStatus.EXECUTE:
                # Optional: could warn or auto-coerce, but Jules prefers deterministic validation
                raise ValueError("Status level cannot be EXECUTE if is_executable is False.")

        return self


class DecisionSupportSystem:
    """
    Orchestrator for generating decision packets.
    Integrates multiple system components to provide a unified 'Go/No-Go' view.
    """

    def __init__(self) -> None:
        self.explainer = SignalExplainer()

    def assemble_packet(
        self,
        symbol: str,
        explanation: SignalExplanation,
        regime_info: RegimeInfo,
        macro_risk: RiskStatus,
        performance_metrics: dict[str, Any],
    ) -> DecisionPacket:
        """
        Assemble a complete decision packet from system components.
        """
        blocking_reasons = []

        # 1. Check Execution Filters
        if not explanation.execution_summary.passed:
            blocking_reasons.append(f"Execution: {explanation.execution_summary.summary}")

        # 2. Check Risk Manager Assessment
        if not explanation.risk_assessment.passed:
            reasons = ", ".join(explanation.risk_assessment.rejection_reasons)
            blocking_reasons.append(f"Risk: {reasons}")

        # 3. Check Macro Event Blocks
        if macro_risk.is_blocked:
            blocking_reasons.append(f"Macro: {macro_risk.reason}")

        # Determine if executable
        is_executable = len(blocking_reasons) == 0

        # Calculate Scores
        c_score, r_score, rs_score = self._calculate_decomposed_scores(
            explanation, regime_info, macro_risk
        )
        decision_score = float(min(max(c_score + r_score + rs_score, 0.0), 100.0))

        # Calculate Consensus
        consensus = self._calculate_consensus(explanation)

        # Determine Augmented Status Level and Review Flag
        status_level = DecisionStatus.BLOCKED
        requires_review = False

        if is_executable:
            if decision_score >= 80.0:
                status_level = DecisionStatus.EXECUTE
            elif decision_score >= 70.0:
                status_level = DecisionStatus.REVIEW
                requires_review = True
            else:
                status_level = DecisionStatus.CAUTION
                requires_review = True

        # Calculate Sizing Multiplier
        sizing_multiplier = self._calculate_sizing_multiplier(
            decision_score, status_level, macro_risk
        )

        # Construct Performance Context
        performance = PerformanceContext(
            sharpe_ratio=performance_metrics.get("sharpe_ratio", 0.0),
            profit_factor=performance_metrics.get("profit_factor", 0.0),
            recovery_factor=performance_metrics.get("recovery_factor", 0.0),
            win_rate=performance_metrics.get("win_rate", 0.0),
            win_loss_ratio=performance_metrics.get("win_loss_ratio", 0.0),
            sortino_ratio=performance_metrics.get("sortino_ratio", 0.0),
            calmar_ratio=performance_metrics.get("calmar_ratio", 0.0),
            expectancy=performance_metrics.get("expectancy", 0.0),
            sqn=performance_metrics.get("sqn", 0.0),
            max_drawdown=performance_metrics.get("max_drawdown", 0.0),
            cvar_95=performance_metrics.get("cvar_95", 0.0),
            total_trades=int(performance_metrics.get("total_trades", 0)),
        )

        # Generate executive summary
        executive_summary = self._generate_executive_summary(
            symbol,
            explanation,
            regime_info,
            status_level,
            decision_score,
            blocking_reasons,
            consensus,
            performance,
        )

        return DecisionPacket(
            symbol=symbol,
            direction=explanation.direction,
            consensus=consensus,
            status_level=status_level,
            decision_score=decision_score,
            consensus_score=c_score,
            regime_score=r_score,
            risk_score=rs_score,
            sizing_multiplier=sizing_multiplier,
            is_executable=is_executable,
            requires_review=requires_review,
            blocking_reasons=blocking_reasons,
            executive_summary=executive_summary,
            explanation=explanation,
            regime=regime_info,
            macro_risk=macro_risk,
            performance=performance,
        )

    def _generate_executive_summary(
        self,
        symbol: str,
        explanation: SignalExplanation,
        regime: RegimeInfo,
        status: DecisionStatus,
        score: float,
        blocking_reasons: list[str],
        consensus: str,
        performance: PerformanceContext,
    ) -> str:
        """
        Generate a concise executive summary for the operator.
        """
        if status == DecisionStatus.BLOCKED:
            reasons = "; ".join(blocking_reasons)
            return f"Trade for {symbol} BLOCKED. Rationale: {reasons}"

        dir_str = explanation.direction.name
        summary = f"Institutional {dir_str} signal for {symbol} with a decision score of {score:.1f}/100. "
        summary += f"Current market state is {regime.label.value.upper()} (Confidence: {regime.confidence:.1%}). "

        # Consensus Insight
        summary += f"Model consensus is {consensus}. "

        # Performance Context Enrichment
        if performance.total_trades > 0:
            summary += f"Strategy performance is stable (Sharpe: {performance.sharpe_ratio:.2f}, WR: {performance.win_rate:.1%}). "

        # Strategic Confluence Enrichment
        alignment = explanation.regime_context.regime_alignment_score
        if alignment >= 0.8:
            summary += "Strategic alignment is EXCEPTIONAL, providing high statistical confidence. "
        elif alignment >= 0.6:
            summary += "Strategic alignment is strong, indicating favorable market conditions. "
        else:
            summary += "Strategic alignment is weak or divergent, suggesting non-ideal conditions. "

        if status == DecisionStatus.EXECUTE:
            summary += "Signal demonstrates maximum confluence and satisfies all institutional guardrails for automated execution."
        elif status == DecisionStatus.REVIEW:
            summary += "Signal is technically valid but requires manual oversight due to moderate confidence or specific risk factors."
        elif status == DecisionStatus.CAUTION:
            summary += "Signal carries elevated operational risk; reduced sizing or manual rejection is recommended."

        return summary

    def _calculate_decomposed_scores(
        self, explanation: SignalExplanation, regime: RegimeInfo, macro_risk: RiskStatus
    ) -> tuple[float, float, float]:
        """
        Calculate decomposed scores for the decision quality.
        Weights:
        - Ensemble Consensus: 40%
        - Regime Confidence: 30%
        - Risk/Reward Quality & Macro Safety: 30%
        """
        # 1. Consensus Score (0-40)
        total_weight = sum(attr.weight for attr in explanation.model_attributions)
        consensus_strength = 0.0
        if total_weight > 0:
            weighted_votes = sum(
                attr.weight
                for attr in explanation.model_attributions
                if attr.vote == explanation.direction
            )
            consensus_strength = weighted_votes / total_weight
        consensus_score = consensus_strength * 40.0

        # 2. Regime Score (0-30)
        regime_score = regime.confidence * 30.0

        # 3. Risk & Safety Score (0-30)
        # Weights: 20% for Risk/Reward quality, 10% for Macro safety
        rr = explanation.risk_assessment.risk_reward_ratio
        rr_quality = min(max(rr, 0.0) / 3.0, 1.0) * 20.0
        macro_safety = min(max(macro_risk.risk_multiplier, 0.0), 1.0) * 10.0
        risk_score = min(rr_quality + macro_safety, 30.0)

        return float(consensus_score), float(regime_score), float(risk_score)

    def _calculate_decision_score(
        self, explanation: SignalExplanation, regime: RegimeInfo, macro_risk: RiskStatus
    ) -> float:
        """
        Legacy method for backward compatibility. Use _calculate_decomposed_scores.
        """
        c, r, rs = self._calculate_decomposed_scores(explanation, regime, macro_risk)
        return float(min(max(c + r + rs, 0.0), 100.0))

    def _calculate_sizing_multiplier(
        self, score: float, status: DecisionStatus, macro_risk: RiskStatus
    ) -> float:
        """
        Determine recommended sizing based on decision quality and macro risk.
        """
        if status == DecisionStatus.BLOCKED:
            return 0.0

        # Base multiplier from score
        base_mult = (score / 100.0) ** 1.5  # Non-linear scaling

        # Apply caution/review penalty
        if status in [DecisionStatus.CAUTION, DecisionStatus.REVIEW]:
            base_mult *= 0.5

        # Apply macro risk multiplier
        final_mult = base_mult * macro_risk.risk_multiplier

        return float(min(max(final_mult, 0.0), 1.0))

    def _calculate_consensus(self, explanation: SignalExplanation) -> str:
        """
        Determine the level of agreement among ensemble models using weighted votes.
        """
        if not explanation.model_attributions:
            return "No Votes"

        direction = explanation.direction
        total_weight = sum(attr.weight for attr in explanation.model_attributions)
        if total_weight <= 0:
            return "No Weight"

        weighted_votes = sum(
            attr.weight for attr in explanation.model_attributions if attr.vote == direction
        )

        agreement_pct = weighted_votes / total_weight

        if agreement_pct >= 1.0:
            return "💎 Unanimous"
        if agreement_pct >= 0.66:
            return "💪 Strong Majority"
        if agreement_pct >= 0.5:
            return "⚖️ Mixed Confluence"
        return "⚠️ Divided/Weak"

    def format_for_operator(self, packet: DecisionPacket, console: Any | None = None) -> str:
        """
        Generate a human-readable, high-fidelity terminal dashboard.
        Aggregates all dimensions of the decision into a single visual summary.
        """
        try:
            from rich import box
            from rich.console import Console, Group
            from rich.panel import Panel
            from rich.progress_bar import ProgressBar
            from rich.table import Table
            from rich.text import Text

            # 1. Header with Augmented Status
            status_colors = {
                DecisionStatus.EXECUTE: "green",
                DecisionStatus.REVIEW: "cyan",
                DecisionStatus.CAUTION: "yellow",
                DecisionStatus.BLOCKED: "red",
            }
            status_icons = {
                DecisionStatus.EXECUTE: "✅ ",
                DecisionStatus.REVIEW: "🔍 ",
                DecisionStatus.CAUTION: "⚠️ ",
                DecisionStatus.BLOCKED: "🛑 ",
            }
            status_color = status_colors.get(packet.status_level, "white")
            status_text = packet.status_level.value.upper()
            status_icon = status_icons.get(packet.status_level, "")

            dir_color = (
                "green"
                if packet.direction == SignalDirection.BUY
                else "red"
                if packet.direction == SignalDirection.SELL
                else "yellow"
            )
            dir_icon = (
                "📈 "
                if packet.direction == SignalDirection.BUY
                else "📉 "
                if packet.direction == SignalDirection.SELL
                else "⏸️ "
            )

            header_content = Text()
            header_content.append("📍 ", style="white")
            header_content.append(f"SYMBOL: {packet.symbol}  ", style="bold")
            header_content.append(dir_icon, style=dir_color)
            header_content.append(
                f"DIRECTION: {packet.direction.name}\n", style=f"bold {dir_color}"
            )
            header_content.append("STATUS: ", style="bold")
            header_content.append(f"{status_icon}{status_text}", style=f"bold {status_color}")
            header_content.append("  |  CONSENSUS: ", style="bold")
            header_content.append(packet.consensus.upper(), style="bold cyan")

            if packet.requires_review:
                header_content.append("\n[REVIEW REQUIRED]", style="bold yellow")

            blocking_panel = None
            if packet.blocking_reasons:
                blocking_content = Text()
                for reason in packet.blocking_reasons:
                    blocking_content.append(f" 🚫 {reason}\n", style="bold red")

                blocking_panel = Panel(
                    blocking_content,
                    title="[bold red]Execution Blocked[/bold red]",
                    border_style="red",
                    box=box.HEAVY,
                )

            title = "💠 [bold]Institutional Decision Support[/bold]"
            if packet.decision_score >= 90.0 and packet.is_executable:
                title = "💠 [bold]Institutional Decision Support [💎 HIGH CONVICTION][/bold]"

            header = Panel(
                header_content,
                title=title,
                subtitle=packet.timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"),
                border_style=status_color,
                box=box.DOUBLE,
            )

            # 1b. Augmented Score Panel
            score_color = (
                "green"
                if packet.decision_score >= 80
                else "yellow"
                if packet.decision_score >= 50
                else "red"
            )
            score_content = Table.grid(expand=True)
            score_content.add_column(ratio=2)
            score_content.add_column(ratio=3)

            score_text = Text()
            score_text.append("Decision Score: ", style="bold")
            score_text.append(f"{packet.decision_score:.1f}/100", style=f"bold {score_color}")
            score_text.append("\n💰 Sizing Rec:  ", style="bold")
            score_text.append(f"{packet.sizing_multiplier:.1%}", style="bold cyan")

            if packet.decision_score >= 85.0 and packet.is_executable:
                score_text.append("\n[HIGH CONVICTION] 💎💎💎", style="bold green")
            elif packet.decision_score >= 70.0 and packet.is_executable:
                score_text.append("\n[STRONG CONVICTION] 💎", style="bold green")

            # Conviction Meter
            meter = ProgressBar(
                total=100,
                completed=packet.decision_score,
                width=40,
                pulse=False,
                style="dim",
                complete_style=score_color,
            )

            score_content.add_row(
                score_text,
                Panel(Group(Text("Conviction Meter", style="dim center"), meter), box=box.SIMPLE),
            )

            augmentation_panel = Panel(
                score_content, title="🎯 Augmentation Metrics", border_style="blue"
            )

            # Executive Summary Panel
            exec_summary_panel = Panel(
                Text(packet.executive_summary, style="italic"),
                title="📝 Executive Summary",
                border_style="white",
            )

            # 2. Market and Performance Overview (Two-column table)
            overview_table = Table.grid(expand=True)
            overview_table.add_column(ratio=1)
            overview_table.add_column(ratio=1)

            # Left Column: Regime
            alignment_color = (
                "green"
                if packet.explanation.regime_context.regime_alignment_score >= 0.7
                else "yellow"
                if packet.explanation.regime_context.regime_alignment_score >= 0.5
                else "red"
            )
            regime_content = (
                f"🏷️ Label: [bold cyan]{packet.regime.label.value.upper()}[/bold cyan]\n"
                f"🎯 Confidence: [bold]{packet.regime.confidence:.1%}[/bold]\n"
                f"🌪️ Volatility: [bold]{packet.regime.volatility_index:.2f}[/bold]\n"
                f"🔄 Transition: {packet.regime.transition_score:.2f}\n"
                f"⚖️ Alignment: [bold {alignment_color}]{packet.explanation.regime_context.regime_alignment_score:.1%}[/bold {alignment_color}]"
            )
            regime_panel = Panel(regime_content, title="🌐 Market Regime", border_style="cyan")

            # Right Column: Performance with Color-Coded Metrics
            def get_color(val: float, green_thr: float, yellow_thr: float) -> str:
                if val >= green_thr:
                    return "green"
                if val >= yellow_thr:
                    return "yellow"
                return "red"

            sharpe_color = get_color(packet.performance.sharpe_ratio, 2.0, 1.0)
            sortino_color = get_color(packet.performance.sortino_ratio, 2.0, 1.0)
            pf_color = get_color(packet.performance.profit_factor, 2.0, 1.5)
            rf_color = get_color(packet.performance.recovery_factor, 3.0, 2.0)
            calmar_color = get_color(packet.performance.calmar_ratio, 3.0, 1.5)
            wr_color = get_color(packet.performance.win_rate, 0.55, 0.45)
            wl_color = get_color(packet.performance.win_loss_ratio, 2.0, 1.2)
            sqn_color = get_color(packet.performance.sqn, 3.0, 2.0)
            cvar_color = (
                "green"
                if packet.performance.cvar_95 >= -0.02
                else "yellow"
                if packet.performance.cvar_95 >= -0.05
                else "red"
            )

            perf_content = (
                f"📈 Sharpe Ratio:  [bold {sharpe_color}]{packet.performance.sharpe_ratio:.2f}[/]  |  "
                f"🛡️ Sortino: [bold {sortino_color}]{packet.performance.sortino_ratio:.2f}[/]\n"
                f"💰 Profit Factor: [bold {pf_color}]{packet.performance.profit_factor:.2f}[/]  |  "
                f"⚖️ W/L Ratio: [bold {wl_color}]{packet.performance.win_loss_ratio:.2f}[/]\n"
                f"🛡️ Recov. Factor: [bold {rf_color}]{packet.performance.recovery_factor:.2f}[/]  |  "
                f"🌊 Calmar: [bold {calmar_color}]{packet.performance.calmar_ratio:.2f}[/]\n"
                f"🎯 Win Rate:      [bold {wr_color}]{packet.performance.win_rate:.1%}[/]  |  "
                f"🔢 Trades: {packet.performance.total_trades}\n"
                f"💎 SQN Score:     [bold {sqn_color}]{packet.performance.sqn:.2f}[/]  |  "
                f"📉 CVaR(95): [bold {cvar_color}]{packet.performance.cvar_95:.2%}[/]"
            )
            perf_panel = Panel(perf_content, title="📊 Recent Performance", border_style="magenta")

            overview_table.add_row(regime_panel, perf_panel)

            # 3. Macro Risk
            macro_color = "green" if not packet.macro_risk.active_events else "yellow"
            if packet.macro_risk.is_blocked:
                macro_color = "red"

            macro_content = Text()
            if not packet.macro_risk.active_events:
                macro_content.append("No active macro events identified.", style="green")
            else:
                macro_content.append(
                    f"Active Events: {len(packet.macro_risk.active_events)}\n", style="bold"
                )
                for event in packet.macro_risk.active_events:
                    impact_color = "red" if event.impact >= 3 else "yellow"
                    macro_content.append(f" • {event.name} ", style="white")
                    macro_content.append(f"[{event.impact}]", style=impact_color)
                    macro_content.append(f" at {event.timestamp.strftime('%H:%M')}\n")

            if packet.macro_risk.reason:
                macro_content.append(f"\nInsight: {packet.macro_risk.reason}", style="italic")

            macro_panel = Panel(
                macro_content, title="🌍 Macro Intelligence", border_style=macro_color
            )

            # 4. Attribution Summary (Text)
            attribution_summary = Panel(
                Text(packet.explanation.human_readable_summary),
                title="🔍 Signal Attribution Summary",
                border_style="yellow",
            )

            # Assemble everything into a single group for output
            components = [header]
            if blocking_panel:
                components.append(blocking_panel)

            components.extend(
                [
                    augmentation_panel,
                    exec_summary_panel,
                    overview_table,
                    macro_panel,
                    attribution_summary,
                    Text("\n[bold]DETAILED ATTRIBUTION BREAKDOWN[/bold]\n"),
                    self.explainer.get_renderable(packet.explanation),
                ]
            )

            dashboard = Group(*components)

            # Print to console if provided
            if console:
                console.print(dashboard)
                return ""

            # Return string representation
            temp_console = Console(force_terminal=True, width=100)
            with temp_console.capture() as capture:
                temp_console.print(dashboard)
            return capture.get()

        except ImportError:
            # Fallback to plain text
            res = f"=== DECISION PACKET: {packet.symbol} ===\n"
            res += f"STATUS: {packet.status_level.value.upper()}\n"
            res += f"DECISION SCORE: {packet.decision_score:.1f}/100 | SIZING: {packet.sizing_multiplier:.1%}\n"
            res += f"DIRECTION: {packet.direction.name} | CONSENSUS: {packet.consensus}\n"

            if packet.requires_review:
                res += "!!! REVIEW REQUIRED !!!\n"

            res += f"EXECUTIVE SUMMARY: {packet.executive_summary}\n"

            if packet.blocking_reasons:
                res += "BLOCKING REASONS:\n"
                for r in packet.blocking_reasons:
                    res += f" • {r}\n"

            res += f"\nREGIME: {packet.regime.label.value} (Confidence: {packet.regime.confidence:.1%}, Vol: {packet.regime.volatility_index:.2f})\n"
            res += (
                f"PERFORMANCE: Sharpe {packet.performance.sharpe_ratio:.2f} | "
                f"PF {packet.performance.profit_factor:.2f} | "
                f"RF {packet.performance.recovery_factor:.2f} | "
                f"Win% {packet.performance.win_rate:.1%} | "
                f"W/L {packet.performance.win_loss_ratio:.2f}\n"
            )
            res += f"MACRO: {'BLOCKED' if packet.macro_risk.is_blocked else 'OK'} (Insight: {packet.macro_risk.reason})\n"

            res += f"\nATTRIBUTION SUMMARY:\n{packet.explanation.human_readable_summary}\n"

            return res
