"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/core/trade_logger.py
Trade logging system using SQLAlchemy ORM with SQLite.
Author : triqbit
License: MIT
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

import numpy as np
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
    select,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from src.core.audit_log import get_audit_logger
from src.core.database import get_engine, get_session_factory
from src.core.profiler import profile

logger = logging.getLogger(__name__)


class Base(DeclarativeBase):
    """Base class for SQLAlchemy models."""

    pass


class AuditMixin:
    """Audit columns as per DATABASE_STANDARDS.md."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )
    created_by: Mapped[str | None] = mapped_column(String(100), nullable=True)
    updated_by: Mapped[str | None] = mapped_column(String(100), nullable=True)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    is_deleted: Mapped[bool] = mapped_column(Boolean, default=False, index=True)


class ModelSignal(Base, AuditMixin):
    """Logs every signal generated by the AI models."""

    __tablename__ = "model_signals"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[int] = mapped_column(nullable=False)  # +1 buy, -1 sell, 0 hold
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float | None] = mapped_column(Float)
    take_profit: Mapped[float | None] = mapped_column(Float)
    lot_size: Mapped[float | None] = mapped_column(Float)
    algorithm: Mapped[str | None] = mapped_column(String(50))
    confidence: Mapped[float | None] = mapped_column(Float)
    volatility: Mapped[float | None] = mapped_column(Float)
    trace_id: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(UTC))

    # Relationship
    trade: Mapped["Trade"] = relationship("Trade", back_populates="signal", uselist=False)
    blocked_analysis: Mapped["BlockedSignalAnalysis"] = relationship(
        "BlockedSignalAnalysis", back_populates="signal", uselist=False
    )

    __table_args__ = (
        CheckConstraint("entry_price > 0", name="check_signal_entry_price_positive"),
        CheckConstraint("lot_size >= 0", name="check_signal_lot_size_non_negative"),
    )


class Trade(Base, AuditMixin):
    """Logs every executed trade."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    ticket: Mapped[int] = mapped_column(unique=True, index=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[int] = mapped_column(nullable=False)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float | None] = mapped_column(Float)
    lot_size: Mapped[float] = mapped_column(Float, nullable=False)
    pnl: Mapped[float] = mapped_column(Float, default=0.0)
    drawdown_impact: Mapped[float | None] = mapped_column(Float)  # impact on total drawdown
    trace_id: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    status: Mapped[str] = mapped_column(
        String(20), default="OPEN", index=True
    )  # OPEN, CLOSED, CANCELLED

    signal_id: Mapped[int | None] = mapped_column(ForeignKey("model_signals.id"))
    signal: Mapped["ModelSignal"] = relationship("ModelSignal", back_populates="trade")

    # Execution analytics relationship
    execution_quality: Mapped["ExecutionQuality"] = relationship(
        "ExecutionQuality", back_populates="trade", uselist=False
    )

    __table_args__ = (
        CheckConstraint("entry_price > 0", name="check_trade_entry_price_positive"),
        CheckConstraint("lot_size > 0", name="check_trade_lot_size_positive"),
    )


class BlockedSignalAnalysis(Base, AuditMixin):
    """Opportunity cost analytics for signals that were rejected."""

    __tablename__ = "blocked_signal_analysis"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    signal_id: Mapped[int] = mapped_column(
        ForeignKey("model_signals.id"), nullable=False, unique=True
    )

    opportunity_cost_pnl: Mapped[float] = mapped_column(Float, nullable=False)
    max_favorable_excursion: Mapped[float] = mapped_column(Float, nullable=False)
    max_adverse_excursion: Mapped[float] = mapped_column(Float, nullable=False)
    would_have_won: Mapped[bool] = mapped_column(Boolean, nullable=False)
    rejection_reason: Mapped[str | None] = mapped_column(String(200))

    # Relationship
    signal: Mapped["ModelSignal"] = relationship("ModelSignal", back_populates="blocked_analysis")


class ExecutionQuality(Base, AuditMixin):
    """Stores high-precision execution analytics for each trade."""

    __tablename__ = "execution_qualities"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    trade_id: Mapped[int] = mapped_column(ForeignKey("trades.id"), nullable=False, unique=True)

    slippage_pips: Mapped[float] = mapped_column(Float, nullable=False)
    execution_latency_ms: Mapped[float] = mapped_column(Float, nullable=False)
    fill_quality_score: Mapped[float] = mapped_column(Float, nullable=False)
    edge_capture: Mapped[float] = mapped_column(Float, nullable=False)
    timing_efficiency: Mapped[float] = mapped_column(Float, nullable=False)
    alpha_decay_pips: Mapped[float] = mapped_column(Float, nullable=False)
    execution_cost_pips: Mapped[float] = mapped_column(Float, nullable=False)
    broker_slippage_pips: Mapped[float] = mapped_column(Float, nullable=True)
    effective_spread_pips: Mapped[float] = mapped_column(Float, nullable=True)
    session: Mapped[str | None] = mapped_column(String(20))

    # Detailed markouts (stored as JSON string for simplicity in SQLite)
    markout_data: Mapped[str | None] = mapped_column(Text)

    # Relationship
    trade: Mapped["Trade"] = relationship("Trade", back_populates="execution_quality")


class RiskEvent(Base, AuditMixin):
    """Logs risk management events (rejections, circuit breakers)."""

    __tablename__ = "risk_events"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    description: Mapped[str | None] = mapped_column(Text)
    symbol: Mapped[str | None] = mapped_column(String(20), index=True)

    signal_id: Mapped[int | None] = mapped_column(ForeignKey("model_signals.id"), nullable=True)


class PerformanceMetric(Base, AuditMixin):
    """Periodic performance snapshots."""

    __tablename__ = "performance_metrics"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), index=True
    )
    sharpe_ratio: Mapped[float | None] = mapped_column(Float)
    profit_factor: Mapped[float | None] = mapped_column(Float)
    max_drawdown: Mapped[float | None] = mapped_column(Float)
    total_trades: Mapped[int | None] = mapped_column(Integer)
    win_rate: Mapped[float | None] = mapped_column(Float)

    __table_args__ = (
        CheckConstraint("win_rate >= 0 AND win_rate <= 1", name="check_performance_win_rate_range"),
        CheckConstraint("profit_factor >= 0", name="check_performance_profit_factor_non_negative"),
    )


class TradeLogger:
    """Enterprise trade logging interface."""

    def __init__(self, db_url: str = "sqlite:///trades.db") -> None:
        self.engine = get_engine(db_url)
        # Create tables if they don't exist
        Base.metadata.create_all(self.engine)
        self.Session = get_session_factory(self.engine)
        # Caching performance report to avoid O(N) DB queries on every signal
        self._perf_cache: dict[str, float] | None = None

    def log_signal(self, signal_data: dict[str, Any]) -> int:
        """Log a new model signal and return its ID."""
        import structlog.contextvars

        trace_id = structlog.contextvars.get_contextvars().get("trace_id")

        with self.Session() as session:
            signal = ModelSignal(
                symbol=signal_data["symbol"],
                direction=signal_data["direction"],
                entry_price=signal_data["entry_price"],
                stop_loss=signal_data.get("stop_loss"),
                take_profit=signal_data.get("take_profit"),
                lot_size=signal_data.get("lot_size"),
                algorithm=signal_data.get("algorithm"),
                confidence=signal_data.get("confidence"),
                volatility=signal_data.get("volatility"),
                trace_id=trace_id,
                timestamp=signal_data.get("timestamp", datetime.now(UTC)),
            )
            session.add(signal)
            session.commit()
            return signal.id

    def log_trade(
        self,
        ticket: int,
        symbol: str,
        direction: int,
        entry_price: float,
        lot_size: float,
        signal_id: int | None = None,
        status: str = "OPEN",
    ) -> int:
        """Log a trade execution."""
        # Invalidate cache if a new closed trade is logged (unlikely to be CLOSED immediately but for safety)
        if status == "CLOSED":
            self._perf_cache = None

        import structlog.contextvars

        trace_id = structlog.contextvars.get_contextvars().get("trace_id")

        with self.Session() as session:
            trade = Trade(
                ticket=ticket,
                symbol=symbol,
                direction=direction,
                entry_price=entry_price,
                lot_size=lot_size,
                signal_id=signal_id,
                trace_id=trace_id,
                status=status,
            )
            session.add(trade)
            session.commit()
            return trade.id

    def update_trade(
        self,
        ticket: int,
        exit_price: float,
        pnl: float | None = None,
        drawdown_impact: float = 0.0,
        trade_obj: Trade | None = None,
    ) -> Trade | None:
        """
        Update a trade when it is closed. Calculates P&L if not provided.

        Args:
            ticket: MT5 ticket ID.
            exit_price: Price at which the trade was closed.
            pnl: Optional realized P&L. Calculated if not provided.
            drawdown_impact: Impact on total drawdown.
            trade_obj: Optional already-fetched Trade ORM object to avoid redundant query.

        Returns:
            The updated Trade object or None if not found.
        """
        # Invalidate cache since a trade is being closed
        self._perf_cache = None

        with self.Session() as session:
            if trade_obj:
                # Merge the object into the current session if it was fetched elsewhere
                trade = session.merge(trade_obj)
            else:
                trade = session.execute(
                    select(Trade).where(Trade.ticket == ticket, Trade.is_deleted.is_(False))
                ).scalar_one_or_none()

            if trade:
                trade.exit_price = exit_price
                if pnl is not None:
                    trade.pnl = pnl
                else:
                    # Basic P&L calculation: (exit - entry) * direction * lot_size * contract_size
                    # For XAUUSD, contract size is often 100.
                    contract_size = 100
                    trade.pnl = (
                        (exit_price - trade.entry_price)
                        * trade.direction
                        * trade.lot_size
                        * contract_size
                    )
                trade.drawdown_impact = drawdown_impact
                trade.status = "CLOSED"
                session.commit()
                # Refresh to ensure P&L and other calculated fields are available
                session.refresh(trade)

                # Audit the outcome
                try:
                    audit = get_audit_logger()
                    audit.log_trade_outcome(
                        ticket=ticket,
                        symbol=trade.symbol,
                        pnl=trade.pnl,
                        reason="closed_at_exit",
                        metadata={
                            "entry": trade.entry_price,
                            "exit": exit_price,
                            "lots": trade.lot_size,
                        },
                    )
                except (RuntimeError, ImportError):
                    pass
                return trade
            else:
                logger.warning("Trade with ticket %d not found for update.", ticket)
                return None

    def get_trade_by_ticket(self, ticket: int) -> Trade | None:
        """Retrieve trade details by ticket ID."""
        with self.Session() as session:
            return session.execute(
                select(Trade).where(Trade.ticket == ticket, Trade.is_deleted.is_(False))
            ).scalar_one_or_none()

    def log_risk_event(
        self,
        event_type: str,
        description: str,
        symbol: str | None = None,
        signal_id: int | None = None,
    ) -> None:
        """Log a risk-related event."""
        with self.Session() as session:
            event = RiskEvent(
                event_type=event_type,
                description=description,
                symbol=symbol,
                signal_id=signal_id,
            )
            session.add(event)
            session.commit()

    def read_performance_report(self, persist: bool = False) -> dict[str, float]:
        """
        Calculate key performance metrics from closed trades.
        Returns Sharpe Ratio, Profit Factor, and Max Drawdown.

        Args:
            persist: Whether to save the calculated metrics to the database.
        """
        # Return cached report if available and not persisting
        if self._perf_cache is not None and not persist:
            return self._perf_cache

        with profile("perf_report_total"), self.Session() as session:
            # 1. Database-level aggregation for basic metrics
                # Optimized: use func.sum and func.count to reduce application-side processing
                with profile("perf_report_db_aggregate"):
                    stats = session.execute(
                        select(
                            func.count(Trade.id).label("total"),
                            func.sum(Trade.pnl).filter(Trade.pnl > 0).label("gross_profit"),
                            func.sum(Trade.pnl).filter(Trade.pnl < 0).label("gross_loss"),
                            func.count(Trade.id).filter(Trade.pnl > 0).label("wins"),
                        ).where(Trade.status == "CLOSED", Trade.is_deleted.is_(False))
                    ).one()

                total_trades = stats.total or 0
                if total_trades == 0:
                    return {
                        "sharpe_ratio": 0.0,
                        "profit_factor": 0.0,
                        "max_drawdown": 0.0,
                        "win_rate": 0.0,
                        "total_trades": 0,
                    }

                gross_profit = float(stats.gross_profit or 0.0)
                gross_loss = abs(float(stats.gross_loss or 0.0))
                profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")
                win_rate = float(stats.wins or 0) / total_trades

                # 2. Sharpe Ratio and Max Drawdown require the full P&L sequence
                # Still fetch only the necessary column
                with profile("perf_report_db_pnl_fetch"):
                    pnls = np.array(
                        session.execute(
                            select(Trade.pnl)
                            .where(Trade.status == "CLOSED", Trade.is_deleted.is_(False))
                            .order_by(Trade.created_at.asc())
                        )
                        .scalars()
                        .all()
                    )

                with profile("perf_report_math_metrics"):
                    # Sharpe Ratio (assumes risk-free rate = 0, per-trade returns)
                    avg_ret = np.mean(pnls) if len(pnls) > 0 else 0.0
                    if len(pnls) > 1:
                        std_ret = np.std(pnls)
                        sharpe = (avg_ret / std_ret * np.sqrt(252)) if std_ret > 0 else 0.0
                    else:
                        sharpe = 0.0

                    # Max Drawdown
                    equity_curve = np.cumsum(pnls)
                    peak = np.maximum.accumulate(equity_curve)
                    drawdown = peak - equity_curve
                    max_dd = np.max(drawdown) if len(drawdown) > 0 else 0.0

                    # Calmar Ratio (Annualized Return / Max Drawdown)
                    # Rough approximation using mean P&L for annualized return if we don't have clear timeframes
                    # per standard: (mean_pnl * 252) / max_dd
                    calmar = (avg_ret * 252 / max_dd) if max_dd > 0 and len(pnls) > 0 else 0.0

                    # Expectancy: (WinRate * AvgWin) - (LossRate * AvgLoss)
                    avg_win = np.mean(pnls[pnls > 0]) if any(pnls > 0) else 0.0
                    avg_loss = abs(np.mean(pnls[pnls < 0])) if any(pnls < 0) else 0.0
                    expectancy = (win_rate * avg_win) - ((1 - win_rate) * avg_loss)

                metrics = {
                    "sharpe_ratio": float(sharpe),
                    "profit_factor": float(profit_factor),
                    "max_drawdown": float(max_dd),
                    "calmar_ratio": float(calmar),
                    "expectancy": float(expectancy),
                    "win_rate": float(win_rate),
                    "total_trades": int(total_trades),
                }

                # Update cache
                self._perf_cache = metrics

                # Optionally log these metrics to DB
                if persist:
                    with profile("perf_report_db_persist"):
                        metric_record = PerformanceMetric(
                            sharpe_ratio=metrics["sharpe_ratio"],
                            profit_factor=metrics["profit_factor"],
                            max_drawdown=metrics["max_drawdown"],
                            total_trades=metrics["total_trades"],
                            win_rate=metrics["win_rate"],
                        )
                        session.add(metric_record)
                        session.commit()

                return metrics
