"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/core/trade_logger.py
Trade logging system using SQLAlchemy ORM with SQLite/PostgreSQL.
Author : triqbit
License: MIT
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

import numpy as np
from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    select,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship, sessionmaker

from src.core.audit_log import get_audit_logger
from src.core.database import Base, AuditMixin, create_resilient_engine, with_db_retry

logger = logging.getLogger(__name__)


class ModelSignal(Base, AuditMixin):
    """Logs every signal generated by the AI models."""

    __tablename__ = "model_signals"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[int] = mapped_column(nullable=False)  # +1 buy, -1 sell, 0 hold
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float | None] = mapped_column(Float)
    take_profit: Mapped[float | None] = mapped_column(Float)
    lot_size: Mapped[float | None] = mapped_column(Float)
    algorithm: Mapped[str | None] = mapped_column(String(50))
    confidence: Mapped[float | None] = mapped_column(Float)
    volatility: Mapped[float | None] = mapped_column(Float)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(UTC))

    # Relationship
    trade: Mapped["Trade"] = relationship("Trade", back_populates="signal", uselist=False)

    __table_args__ = (
        CheckConstraint("entry_price > 0", name="check_signal_entry_price_positive"),
        CheckConstraint("lot_size >= 0", name="check_signal_lot_size_non_negative"),
    )


class Trade(Base, AuditMixin):
    """Logs every executed trade."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    ticket: Mapped[int] = mapped_column(unique=True, index=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[int] = mapped_column(nullable=False)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float | None] = mapped_column(Float)
    lot_size: Mapped[float] = mapped_column(Float, nullable=False)
    pnl: Mapped[float] = mapped_column(Float, default=0.0)
    drawdown_impact: Mapped[float | None] = mapped_column(Float)  # impact on total drawdown
    status: Mapped[str] = mapped_column(String(20), default="OPEN", index=True)  # OPEN, CLOSED, CANCELLED

    signal_id: Mapped[int | None] = mapped_column(ForeignKey("model_signals.id"))
    signal: Mapped["ModelSignal"] = relationship("ModelSignal", back_populates="trade")

    __table_args__ = (
        CheckConstraint("entry_price > 0", name="check_trade_entry_price_positive"),
        CheckConstraint("lot_size > 0", name="check_trade_lot_size_positive"),
    )


class RiskEvent(Base, AuditMixin):
    """Logs risk management events (rejections, circuit breakers)."""

    __tablename__ = "risk_events"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    symbol: Mapped[str | None] = mapped_column(String(20))

    signal_id: Mapped[int | None] = mapped_column(ForeignKey("model_signals.id"), nullable=True)


class PerformanceMetric(Base, AuditMixin):
    """Periodic performance snapshots."""

    __tablename__ = "performance_metrics"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(UTC))
    sharpe_ratio: Mapped[float | None] = mapped_column(Float)
    profit_factor: Mapped[float | None] = mapped_column(Float)
    max_drawdown: Mapped[float | None] = mapped_column(Float)
    total_trades: Mapped[int | None] = mapped_column(Integer)
    win_rate: Mapped[float | None] = mapped_column(Float)


class TradeLogger:
    """Enterprise trade logging interface with resilient database handling."""

    def __init__(self, db_url: str = "sqlite:///trades.db") -> None:
        self.engine = create_resilient_engine(db_url)
        # In production, we favor Alembic migrations, but for ease of use/testing:
        if "sqlite" in db_url:
            Base.metadata.create_all(self.engine)

        self.Session = sessionmaker(bind=self.engine)
        # Caching performance report to avoid O(N) DB queries on every signal
        self._perf_cache: dict[str, float] | None = None

    @with_db_retry()
    def log_signal(self, signal_data: dict[str, Any]) -> int:
        """Log a new model signal and return its ID."""
        with self.Session() as session:
            signal = ModelSignal(
                symbol=signal_data["symbol"],
                direction=signal_data["direction"],
                entry_price=signal_data["entry_price"],
                stop_loss=signal_data.get("stop_loss"),
                take_profit=signal_data.get("take_profit"),
                lot_size=signal_data.get("lot_size"),
                algorithm=signal_data.get("algorithm"),
                confidence=signal_data.get("confidence"),
                volatility=signal_data.get("volatility"),
                timestamp=signal_data.get("timestamp", datetime.now(UTC)),
            )
            session.add(signal)
            session.commit()
            return signal.id

    @with_db_retry()
    def log_trade(
        self,
        ticket: int,
        symbol: str,
        direction: int,
        entry_price: float,
        lot_size: float,
        signal_id: int | None = None,
        status: str = "OPEN",
    ) -> int:
        """Log a trade execution."""
        # Invalidate cache if a new closed trade is logged
        if status == "CLOSED":
            self._perf_cache = None

        with self.Session() as session:
            trade = Trade(
                ticket=ticket,
                symbol=symbol,
                direction=direction,
                entry_price=entry_price,
                lot_size=lot_size,
                signal_id=signal_id,
                status=status,
            )
            session.add(trade)
            session.commit()
            return trade.id

    @with_db_retry()
    def update_trade(
        self,
        ticket: int,
        exit_price: float,
        pnl: float | None = None,
        drawdown_impact: float = 0.0,
    ) -> None:
        """Update a trade when it is closed. Calculates P&L if not provided."""
        # Invalidate cache since a trade is being closed
        self._perf_cache = None

        with self.Session() as session:
            trade = (
                session.query(Trade)
                .filter(Trade.ticket == ticket, Trade.is_deleted.is_(False))
                .first()
            )
            if trade:
                trade.exit_price = exit_price
                if pnl is not None:
                    trade.pnl = pnl
                else:
                    # Basic P&L calculation: (exit - entry) * direction * lot_size * contract_size
                    contract_size = 100
                    trade.pnl = (
                        (exit_price - trade.entry_price)
                        * trade.direction
                        * trade.lot_size
                        * contract_size
                    )
                trade.drawdown_impact = drawdown_impact
                trade.status = "CLOSED"
                session.commit()

                # Audit the outcome
                try:
                    audit = get_audit_logger()
                    audit.log_trade_outcome(
                        ticket=ticket,
                        symbol=trade.symbol,
                        pnl=trade.pnl,
                        reason="closed_at_exit",
                        metadata={
                            "entry": trade.entry_price,
                            "exit": exit_price,
                            "lots": trade.lot_size,
                        },
                    )
                except (RuntimeError, ImportError):
                    pass
            else:
                logger.warning("Trade with ticket %d not found for update.", ticket)

    @with_db_retry()
    def get_trade_by_ticket(self, ticket: int) -> Trade | None:
        """Retrieve trade details by ticket ID."""
        with self.Session() as session:
            return (
                session.query(Trade)
                .filter(Trade.ticket == ticket, Trade.is_deleted.is_(False))
                .first()
            )

    @with_db_retry()
    def log_risk_event(
        self,
        event_type: str,
        description: str,
        symbol: str | None = None,
        signal_id: int | None = None,
    ) -> None:
        """Log a risk-related event."""
        with self.Session() as session:
            event = RiskEvent(
                event_type=event_type,
                description=description,
                symbol=symbol,
                signal_id=signal_id,
            )
            session.add(event)
            session.commit()

    @with_db_retry()
    def read_performance_report(self, persist: bool = False) -> dict[str, float]:
        """
        Calculate key performance metrics from closed trades.
        """
        # Return cached report if available and not persisting
        if self._perf_cache is not None and not persist:
            return self._perf_cache

        with self.Session() as session:
            pnls = np.array(
                session.execute(
                    select(Trade.pnl).where(Trade.status == "CLOSED", Trade.is_deleted.is_(False))
                )
                .scalars()
                .all()
            )

            if len(pnls) == 0:
                return {
                    "sharpe_ratio": 0.0,
                    "profit_factor": 0.0,
                    "max_drawdown": 0.0,
                }

            # Profit Factor
            gross_profit = np.sum(pnls[pnls > 0])
            gross_loss = abs(np.sum(pnls[pnls < 0]))
            profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

            # Sharpe Ratio
            if len(pnls) > 1:
                avg_ret = np.mean(pnls)
                std_ret = np.std(pnls)
                sharpe = (avg_ret / std_ret * np.sqrt(252)) if std_ret > 0 else 0.0
            else:
                sharpe = 0.0

            # Max Drawdown
            equity_curve = np.cumsum(pnls)
            peak = np.maximum.accumulate(equity_curve)
            drawdown = peak - equity_curve
            max_dd = np.max(drawdown) if len(drawdown) > 0 else 0.0

            win_rate = float(np.sum(pnls > 0) / len(pnls))
            metrics = {
                "sharpe_ratio": float(sharpe),
                "profit_factor": float(profit_factor),
                "max_drawdown": float(max_dd),
                "win_rate": win_rate,
                "total_trades": len(pnls),
            }

            # Update cache
            self._perf_cache = metrics

            # Optionally log these metrics to DB
            if persist:
                metric_record = PerformanceMetric(
                    sharpe_ratio=metrics["sharpe_ratio"],
                    profit_factor=metrics["profit_factor"],
                    max_drawdown=metrics["max_drawdown"],
                    total_trades=metrics["total_trades"],
                    win_rate=metrics["win_rate"],
                )
                session.add(metric_record)
                session.commit()

            return metrics
