"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/core/trade_logger.py
Trade logging system using SQLAlchemy ORM with SQLite.
Author : triqbit
License: MIT
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

import numpy as np
from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import relationship, sessionmaker

from src.core.audit_log import AuditLogger
from src.core.database import AuditMixin, Base

logger = logging.getLogger(__name__)


class ModelSignal(Base, AuditMixin):
    """Logs every signal generated by the AI models."""

    __tablename__ = "model_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    direction = Column(Integer, nullable=False)  # +1 buy, -1 sell, 0 hold
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    lot_size = Column(Float)
    algorithm = Column(String(50))
    confidence = Column(Float)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationship
    trade = relationship("Trade", back_populates="signal", uselist=False)


class Trade(Base, AuditMixin):
    """Logs every executed trade."""

    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticket = Column(Integer, unique=True, index=True)
    symbol = Column(String(20), nullable=False)
    direction = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float)
    lot_size = Column(Float, nullable=False)
    pnl = Column(Float, default=0.0)
    drawdown_impact = Column(Float)  # impact on total drawdown
    status = Column(String(20), default="OPEN")  # OPEN, CLOSED, CANCELLED

    signal_id = Column(Integer, ForeignKey("model_signals.id"))
    signal = relationship("ModelSignal", back_populates="trade")


class RiskEvent(Base, AuditMixin):
    """Logs risk management events (rejections, circuit breakers)."""

    __tablename__ = "risk_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_type = Column(String(50), nullable=False)
    description = Column(Text)
    symbol = Column(String(20))

    signal_id = Column(Integer, ForeignKey("model_signals.id"), nullable=True)


class PerformanceMetric(Base, AuditMixin):
    """Periodic performance snapshots."""

    __tablename__ = "performance_metrics"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    sharpe_ratio = Column(Float)
    profit_factor = Column(Float)
    max_drawdown = Column(Float)
    total_trades = Column(Integer)
    win_rate = Column(Float)


class TradeLogger:
    """Enterprise trade logging interface."""

    def __init__(self, db_url: str = "sqlite:///trades.db") -> None:
        self.engine = create_engine(db_url)
        Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        self.audit = AuditLogger(self.Session)

    def log_signal(self, signal_data: Dict[str, Any]) -> int:
        """Log a new model signal and return its ID."""
        with self.Session() as session:
            signal = ModelSignal(
                symbol=signal_data["symbol"],
                direction=signal_data["direction"],
                entry_price=signal_data["entry_price"],
                stop_loss=signal_data.get("stop_loss"),
                take_profit=signal_data.get("take_profit"),
                lot_size=signal_data.get("lot_size"),
                algorithm=signal_data.get("algorithm"),
                confidence=signal_data.get("confidence"),
                timestamp=signal_data.get("timestamp", datetime.now(timezone.utc)),
            )
            session.add(signal)
            session.commit()
            return signal.id

    def log_trade(
        self,
        ticket: int,
        symbol: str,
        direction: int,
        entry_price: float,
        lot_size: float,
        signal_id: Optional[int] = None,
        status: str = "OPEN",
    ) -> int:
        """Log a trade execution."""
        with self.Session() as session:
            trade = Trade(
                ticket=ticket,
                symbol=symbol,
                direction=direction,
                entry_price=entry_price,
                lot_size=lot_size,
                signal_id=signal_id,
                status=status,
            )
            session.add(trade)
            session.commit()
            return trade.id

    def update_trade(
        self,
        ticket: int,
        exit_price: float,
        pnl: Optional[float] = None,
        drawdown_impact: float = 0.0,
    ) -> None:
        """Update a trade when it is closed. Calculates P&L if not provided."""
        with self.Session() as session:
            trade = session.query(Trade).filter(Trade.ticket == ticket).first()
            if trade:
                trade.exit_price = exit_price
                if pnl is not None:
                    trade.pnl = pnl
                else:
                    # Basic P&L calculation: (exit - entry) * direction * lot_size * contract_size
                    # For XAUUSD, contract size is often 100.
                    contract_size = 100
                    trade.pnl = (
                        (exit_price - trade.entry_price)
                        * trade.direction
                        * trade.lot_size
                        * contract_size
                    )
                trade.drawdown_impact = drawdown_impact
                trade.status = "CLOSED"
                session.commit()
            else:
                logger.warning("Trade with ticket %d not found for update.", ticket)

    def get_trade_by_ticket(self, ticket: int) -> Optional[Trade]:
        """Retrieve trade details by ticket ID."""
        with self.Session() as session:
            return session.query(Trade).filter(Trade.ticket == ticket).first()

    def log_risk_event(
        self,
        event_type: str,
        description: str,
        symbol: Optional[str] = None,
        signal_id: Optional[int] = None,
    ) -> None:
        """Log a risk-related event."""
        with self.Session() as session:
            event = RiskEvent(
                event_type=event_type,
                description=description,
                symbol=symbol,
                signal_id=signal_id,
            )
            session.add(event)
            session.commit()

    def read_performance_report(self) -> Dict[str, float]:
        """
        Calculate key performance metrics from closed trades.
        Returns Sharpe Ratio, Profit Factor, and Max Drawdown.
        """
        with self.Session() as session:
            trades = session.query(Trade).filter(Trade.status == "CLOSED").all()
            if not trades:
                return {
                    "sharpe_ratio": 0.0,
                    "profit_factor": 0.0,
                    "max_drawdown": 0.0,
                }

            pnls = np.array([t.pnl for t in trades])

            # Profit Factor
            gross_profit = np.sum(pnls[pnls > 0])
            gross_loss = abs(np.sum(pnls[pnls < 0]))
            profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

            # Sharpe Ratio (assumes risk-free rate = 0, per-trade returns)
            if len(pnls) > 1:
                avg_ret = np.mean(pnls)
                std_ret = np.std(pnls)
                sharpe = (avg_ret / std_ret * np.sqrt(252)) if std_ret > 0 else 0.0
            else:
                sharpe = 0.0

            # Max Drawdown
            equity_curve = np.cumsum(pnls)
            peak = np.maximum.accumulate(equity_curve)
            drawdown = peak - equity_curve
            max_dd = np.max(drawdown) if len(drawdown) > 0 else 0.0

            metrics = {
                "sharpe_ratio": float(sharpe),
                "profit_factor": float(profit_factor),
                "max_drawdown": float(max_dd),
            }

            # Optionally log these metrics to DB
            metric_record = PerformanceMetric(
                sharpe_ratio=metrics["sharpe_ratio"],
                profit_factor=metrics["profit_factor"],
                max_drawdown=metrics["max_drawdown"],
                total_trades=len(trades),
                win_rate=float(np.sum(pnls > 0) / len(pnls)),
            )
            session.add(metric_record)
            session.commit()

            return metrics
