"""
MT5 AI/ML Trading Bot - Enterprise Edition
src/models/base.py
Common interfaces and data structures for all AI models.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass

import numpy as np


@dataclass
class Signal:
    """
    Standard trading signal generated by models.
    direction: 1 (Buy), -1 (Sell), 0 (Hold)
    confidence: float between 0.0 and 1.0
    """
    direction: int
    confidence: float


class BaseModel(ABC):
    """
    Abstract base class for all trading models.
    Ensures a consistent interface for the ensemble and execution layers.
    """

    @abstractmethod
    def predict(self, features: np.ndarray) -> Signal:
        """
        Generate a trading signal from input features.

        Args:
            features: Preprocessed market data features.

        Returns:
            Signal: The generated trading signal.
        """
        pass
