from enum import Enum

class MarketRegime(str, Enum):
    TRENDING = "TRENDING"
    RANGING = "RANGING"
    VOLATILE_BREAKOUT = "VOLATILE_BREAKOUT"
    LOW_VOL_DRIFT = "LOW_VOL_DRIFT"
    NEWS_SHOCK = "NEWS_SHOCK"
    MEAN_REVERSION = "MEAN_REVERSION"
